### PR TITLE
Use LINQ OrderBy to sort in BuildNodes

### PR DESCRIPTION
**Pull request by MB512**
As you find out, this is even faster than Array.Sort

### CODE REVIEW

**Comment by viceroypenguin** [comment]
Wow. Epic fail. I had the correct version committed, but a) I didn't copy it to my comment correctly, and b) I didn't push the commit. 🤦🏼‍♂️

Thanks for the PR, but I did have the correct version already done. Take a look now?

**Comment by viceroypenguin** [comment]
PS: If you're good with the latest code, then I'll release v3.1.0 tomorrow with the work done since 3.0.0

**Comment by viceroypenguin** [comment]
Ok, I did screw up. :D Thanks for fixing!

**Comment by MB512** [comment]
Perfect!

I think we can't improve this any more.
(But i am glad if someone prove me wrong)

**Pull request merged**
